[project]
name = "vt"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.29.0",
    "requests-toolbelt>=1.0.0",
    "urllib3<2",
]

[dependency-groups]
dev = [
    "prek>=0.3.3",
    "pytest>=8.4.2",
    "python-dotenv>=1.1.1",
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
